from __future__ import annotations

import subprocess
from hashlib import sha256
from pathlib import Path

import pytest

import openconstraint.opensta as opensta
from openconstraint.cli import _merge_opensta, _mode_semantics
from openconstraint.engine import AuditOptions, ModeInput, audit
from openconstraint.model import Clock, SourceLocation
from openconstraint.opensta import (
    OpenSTAConfig,
    OpenSTAModeConfig,
    OpenSTAModeResult,
    OpenSTANotFoundError,
    OpenSTAValidationResult,
    discover_opensta,
    render_opensta_tcl,
    tcl_quote,
    validate_with_opensta,
)
from openconstraint.parsers.liberty import parse_liberty
from openconstraint.parsers.verilog import elaborate, parse_verilog

OPENSTA_FIXTURE_ROOT = Path(__file__).parent / "fixtures" / "opensta"


def _inputs(tmp_path: Path) -> tuple[Path, Path, Path, Path]:
    paths = (
        tmp_path / "top.v",
        tmp_path / "cells.lib",
        tmp_path / "functional.sdc",
        tmp_path / "scan.sdc",
    )
    for path in paths:
        path.write_text(f"# {path.name}\n", encoding="utf-8", newline="\n")
    return paths


def test_tcl_quote_escapes_substitutions_and_command_injection() -> None:
    value = 'C:\\timing\\bad"; puts [exec pwn] $clock.sdc'

    assert tcl_quote(value) == '"C:\\\\timing\\\\bad\\"; puts \\[exec pwn\\] \\$clock.sdc"'


@pytest.mark.parametrize("value", ["bad\nputs pwn", "bad\rputs pwn", "bad\x00tail"])
def test_tcl_quote_rejects_newlines_and_nul(value: str) -> None:
    with pytest.raises(ValueError):
        tcl_quote(value)


def test_discovery_failure_reports_both_supported_binary_names(monkeypatch: pytest.MonkeyPatch) -> None:
    lookups: list[str] = []

    def missing(candidate: str) -> None:
        lookups.append(candidate)
        return None

    monkeypatch.setattr(opensta.shutil, "which", missing)

    with pytest.raises(OpenSTANotFoundError, match="OpenSTA was not found on PATH"):
        discover_opensta()

    assert lookups == ["sta", "opensta"]


def test_rendered_driver_contains_only_fixed_quoted_commands(tmp_path: Path) -> None:
    verilog = tmp_path / "design [final].v"
    liberty = tmp_path / "cells $slow.lib"
    first_sdc = tmp_path / "base mode.sdc"
    second_sdc = tmp_path / "overrides.sdc"
    effective = tmp_path / "effective output.sdc"
    config = OpenSTAConfig(
        binary="sta",
        timeout=5.0,
        verilog_paths=(str(verilog),),
        liberty_paths=(str(liberty),),
        top='top; puts "not a command"',
    )
    mode = OpenSTAModeConfig("functional", (str(first_sdc), str(second_sdc)))

    driver = render_opensta_tcl(config, mode, effective)
    lines = driver.splitlines()

    assert lines[:2] == ["# Generated by OpenConstraint; do not edit.", "set ::sta_continue_on_error 0"]
    assert f"read_liberty {tcl_quote(liberty)}" in lines
    assert f"read_verilog {tcl_quote(verilog)}" in lines
    assert f"link_design {tcl_quote(config.top)}" in lines
    assert f"read_sdc {tcl_quote(first_sdc)}" in lines
    assert f"read_sdc {tcl_quote(second_sdc)}" in lines
    assert "set ::openconstraint_check_ok [check_setup -verbose]" in lines
    assert f"write_sdc -no_timestamp {tcl_quote(effective.resolve())}" in lines
    assert lines[-4:] == [
        "if {!$::openconstraint_check_ok} {",
        '    puts stderr "OpenConstraint: check_setup reported one or more issues."',
        "    exit 2",
        "}",
    ]
    assert driver.index("check_setup -verbose") < driver.index("write_sdc -no_timestamp")


def test_real_opensta_fixture_is_statically_complete() -> None:
    verilog = OPENSTA_FIXTURE_ROOT / "roundtrip.v"
    liberty = OPENSTA_FIXTURE_ROOT / "roundtrip.lib"
    sdc = OPENSTA_FIXTURE_ROOT / "roundtrip.sdc"
    design = elaborate(parse_verilog([verilog]), parse_liberty(liberty), "opensta_roundtrip")

    result = audit(
        design,
        [ModeInput("default", [str(sdc)])],
        AuditOptions(report_implicit_waveform=False),
    )

    assert result.diagnostics == []
    assert len(result.modes) == 1
    coverage = result.modes[0].coverage
    assert (coverage.score, coverage.grade) == (100.0, "A")
    assert result.modes[0].clocks["core_clk"].waveform is None
    assert result.modes[0].clocks["core_clk"].effective_waveform == (0.0, 5.0)
    assert result.modes[0].clocks["phase_clk"].waveform == (1.0, 3.0)
    components = {component.key: component for component in coverage.components}
    assert {
        key: (component.covered, component.total, component.percentage, component.weight)
        for key, component in components.items()
    } == {
        "sequential_endpoints": (1, 1, 100.0, 0.5),
        "input_delays": (4, 4, 100.0, 0.2),
        "output_delays": (4, 4, 100.0, 0.2),
        "query_health": (5, 5, 100.0, 0.1),
    }


def test_semantic_snapshot_normalizes_implicit_primary_clock_waveform(audit_factory, design_factory) -> None:
    implicit_sdc = """
create_clock -name core -period 10 [get_ports clk]
set_input_delay 1 -clock core [get_ports {clk2 data spare}]
set_output_delay 2 -clock core [all_outputs]
"""
    explicit_sdc = """
current_design top
create_clock -name core -period 10 -waveform {0 5} [get_ports clk]
set_input_delay 1 -clock core [get_ports {clk2 data spare}]
set_output_delay 2 -clock core [all_outputs]
"""
    result = audit_factory(implicit_sdc)
    implicit = result.modes[0]
    explicit = audit_factory(explicit_sdc).modes[0]

    assert implicit.clocks["core"].waveform is None
    assert implicit.clocks["core"].effective_waveform == (0.0, 5.0)
    assert explicit.clocks["core"].waveform == explicit.clocks["core"].effective_waveform == (0.0, 5.0)
    assert _mode_semantics(implicit) == _mode_semantics(explicit)
    reported_clock = result.to_dict()["modes"][0]["clocks"][0]
    assert reported_clock["waveform"] is None
    assert reported_clock["waveform_explicit"] is False

    mode = OpenSTAModeResult(
        mode="default",
        sdc_paths=("constraints.sdc",),
        version="OpenSTA 3.1.0",
        command=("sta", "validate.tcl"),
        stdout="",
        stderr="",
        returncode=0,
        timed_out=False,
        duration_seconds=0.1,
        effective_sdc=explicit_sdc,
        effective_sdc_sha256=sha256(explicit_sdc.encode()).hexdigest(),
    )
    validation = OpenSTAValidationResult(
        config=OpenSTAConfig("sta", 10, ("top.v",), ("cells.lib",), "top"),
        version="OpenSTA 3.1.0",
        modes=(mode,),
    )

    _merge_opensta(result, validation, design_factory(), AuditOptions())

    effective_audit = result.summary["opensta"]["modes"][0]["effective_audit"]
    assert effective_audit["semantic_match"] is True
    assert effective_audit["static_semantic_sha256"] == effective_audit["effective_semantic_sha256"]


@pytest.mark.parametrize("period", [0.0, float("nan"), float("inf")])
def test_effective_waveform_rejects_invalid_implicit_primary_period(period: float) -> None:
    clock = Clock("core", {"clk"}, period, None, False, SourceLocation("constraints.sdc"))

    assert clock.effective_waveform is None


def test_effective_waveform_never_relabels_invalid_explicit_primary() -> None:
    clock = Clock("core", {"clk"}, 10.0, None, True, SourceLocation("constraints.sdc"))

    assert clock.effective_waveform is None


def test_effective_waveform_preserves_derived_generated_clock() -> None:
    clock = Clock(
        "div2",
        {"u_ff/CLK"},
        20.0,
        (0.0, 10.0),
        False,
        SourceLocation("constraints.sdc"),
        generated=True,
    )

    assert clock.effective_waveform == (0.0, 10.0)


def test_effective_waveform_never_synthesizes_invalid_generated_clock() -> None:
    clock = Clock(
        "broken",
        {"u_ff/CLK"},
        20.0,
        None,
        False,
        SourceLocation("constraints.sdc"),
        generated=True,
    )

    assert clock.effective_waveform is None


def test_successful_multi_mode_validation_is_isolated_and_captured(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    verilog, liberty, functional_sdc, scan_sdc = _inputs(tmp_path)
    fake_binary = str((tmp_path / "sta").resolve())
    calls: list[tuple[tuple[str, ...], dict[str, object]]] = []
    drivers: list[str] = []
    effective_payloads = (b"create_clock -period 10 clk\n", b"create_clock -period 20 scan_clk\n")

    monkeypatch.setattr(opensta.shutil, "which", lambda _candidate: fake_binary)

    def run(command: tuple[str, ...], **kwargs: object) -> subprocess.CompletedProcess[str]:
        calls.append((command, kwargs))
        if command[1:] == ("-version",):
            return subprocess.CompletedProcess(command, 0, "OpenSTA 3.0.1\n", "")
        driver_path = Path(command[-1])
        drivers.append(driver_path.read_text(encoding="utf-8"))
        payload = effective_payloads[len(drivers) - 1]
        driver_path.with_name("effective.sdc").write_bytes(payload)
        return subprocess.CompletedProcess(command, 0, f"mode {len(drivers)} stdout\n", "")

    monkeypatch.setattr(opensta.subprocess, "run", run)

    result = validate_with_opensta(
        [verilog],
        [liberty],
        "top",
        {"functional": [functional_sdc], "scan": [scan_sdc]},
        binary="sta",
        timeout=7.5,
    )

    assert result.version == "OpenSTA 3.0.1"
    assert result.succeeded
    assert [mode.mode for mode in result.modes] == ["functional", "scan"]
    assert len(calls) == 3
    for _command, kwargs in calls:
        assert kwargs["shell"] is False
        assert kwargs["timeout"] == 7.5
    for mode, payload in zip(result.modes, effective_payloads, strict=True):
        assert mode.command[1:4] == ("-no_init", "-no_splash", "-exit")
        assert mode.returncode == 0
        assert not mode.timed_out
        assert mode.effective_sdc == payload.decode("utf-8")
        assert mode.effective_sdc_sha256 == sha256(payload).hexdigest()
        assert mode.succeeded
    functional_command = f"read_sdc {tcl_quote(functional_sdc.resolve())}"
    scan_command = f"read_sdc {tcl_quote(scan_sdc.resolve())}"
    assert functional_command in drivers[0]
    assert scan_command not in drivers[0]
    assert scan_command in drivers[1]
    assert functional_command not in drivers[1]
    assert result.modes[0].command[-1] != result.modes[1].command[-1]


def test_nonzero_check_result_preserves_output_and_effective_sdc(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    verilog, liberty, functional_sdc, _ = _inputs(tmp_path)
    fake_binary = str((tmp_path / "sta").resolve())
    payload = b"set_false_path -from a -to b\n"

    monkeypatch.setattr(opensta.shutil, "which", lambda _candidate: fake_binary)

    def run(command: tuple[str, ...], **_kwargs: object) -> subprocess.CompletedProcess[str]:
        if command[1:] == ("-version",):
            return subprocess.CompletedProcess(command, 0, "OpenSTA 3.0.1\n", "")
        Path(command[-1]).with_name("effective.sdc").write_bytes(payload)
        return subprocess.CompletedProcess(command, 2, "check output\n", "setup warnings\n")

    monkeypatch.setattr(opensta.subprocess, "run", run)

    result = validate_with_opensta(
        [verilog], [liberty], "top", {"functional": functional_sdc}, binary="sta", timeout=3.0
    )
    mode = result.modes[0]

    assert not result.succeeded
    assert not mode.succeeded
    assert mode.returncode == mode.return_code == 2
    assert mode.stdout == "check output\n"
    assert mode.stderr == "setup warnings\n"
    assert mode.effective_sdc == payload.decode("utf-8")
    assert mode.effective_sdc_hash == sha256(payload).hexdigest()


def test_mode_timeout_is_a_captured_result(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    verilog, liberty, functional_sdc, _ = _inputs(tmp_path)
    fake_binary = str((tmp_path / "sta").resolve())
    calls: list[tuple[tuple[str, ...], dict[str, object]]] = []

    monkeypatch.setattr(opensta.shutil, "which", lambda _candidate: fake_binary)

    def run(command: tuple[str, ...], **kwargs: object) -> subprocess.CompletedProcess[str]:
        calls.append((command, kwargs))
        if command[1:] == ("-version",):
            return subprocess.CompletedProcess(command, 0, "OpenSTA 3.0.1\n", "")
        raise subprocess.TimeoutExpired(command, 2.25, output=b"partial stdout", stderr=b"partial stderr")

    monkeypatch.setattr(opensta.subprocess, "run", run)

    result = validate_with_opensta(
        [verilog], [liberty], "top", {"functional": functional_sdc}, binary="sta", timeout=2.25
    )
    mode = result.modes[0]

    assert len(calls) == 2
    assert calls[1][1]["timeout"] == 2.25
    assert calls[1][1]["shell"] is False
    assert not result.succeeded
    assert not mode.succeeded
    assert mode.timed_out
    assert mode.returncode is None
    assert mode.stdout == "partial stdout"
    assert mode.stderr == "partial stderr"
    assert mode.effective_sdc is None
    assert mode.effective_sdc_sha256 is None


def test_successful_effective_sdc_is_reaudited_and_new_findings_are_merged(audit_factory, design_factory) -> None:
    result = audit_factory(
        """
create_clock -name core -period 10 -waveform {0 5} [get_ports clk]
set_input_delay 1 -clock core [all_inputs]
set_output_delay 2 -clock core [all_outputs]
"""
    )
    effective_sdc = "create_clock -name core -period 10 -waveform {0 5} [get_ports clk]\n"
    mode = OpenSTAModeResult(
        mode="default",
        sdc_paths=("constraints.sdc",),
        version="OpenSTA 3.0.1",
        command=("sta", "validate.tcl"),
        stdout="",
        stderr="",
        returncode=0,
        timed_out=False,
        duration_seconds=0.1,
        effective_sdc=effective_sdc,
        effective_sdc_sha256=sha256(effective_sdc.encode()).hexdigest(),
    )
    validation = OpenSTAValidationResult(
        config=OpenSTAConfig("sta", 10, ("top.v",), ("cells.lib",), "top"),
        version="OpenSTA 3.0.1",
        modes=(mode,),
    )

    _merge_opensta(result, validation, design_factory(), AuditOptions())

    ids = {finding.rule_id for finding in result.diagnostics}
    effective = result.summary["opensta"]["modes"][0]["effective_audit"]
    assert {"OC3001", "OC3002"} <= ids
    assert effective["diagnostic_count"] >= 2
    assert effective["added_diagnostic_count"] >= 2
    assert not effective["semantic_match"]
    assert len(effective["static_semantic_sha256"]) == 64
    assert len(effective["effective_semantic_sha256"]) == 64
